### ISSUE TITLE
GET institution-jobs filter for person not working

### ISSUE THREAD

**Issue by jordanrueden** [ellucianEthos/postman-ethos-integration#1]
https://integrate.elluciancloud.com/api/institution-jobs?criteria={"endOn":"2013-01-31","person":"08bb7310-0da7-4a0f-b5cc-4fcc516d4d8a"}

Is returning a 400 Bad Request

{
    "errors": [
        {
            "code": "Global.SchemaValidation.Error",
            "description": "Errors parsing input JSON.",
            "message": "'person' is an invalid data type. "
        }
    ]
}

This is an example so I am not sure but I cannot get the criteria to work.

**Comment by danishfastian** [comment]
I think it  should be something like this 
criteria={"person":{"id":"08bb7310-0da7-4a0f-b5cc-4fcc516d4d8a"}}

**Comment by jordanrueden** [comment]
Thanks that works! Just FYI your documentation is missing the id portion of that query.
